% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Jul-2026 11:50:03
%  MATLAB version: 24.1.0.2537033 (R2024a)
% -------------------------------------------------------------------
                                   

%% LONGITUDINAL DYNAMICS (Source: Heffley & Jewell, NASA 1972 AD-A277031;
%% Etkin & Reid, Dynamics of Flight, Wiley 1959 — via TensorAeroSpace F4C model)
%% Flight condition: Mach 0.6, 35,000 ft

Xu = 7.6180e-4;
Xw = 4.7612e-3;
Xq = 0;
Xtheta = -9.8100;

Zu = -6.6657e-2;
Zw = -2.8567e-1;
Zq = 1.8000e2;
Ztheta = 0;

Mu = 1.5124e-3;
Mw = -1.0083e-2;
Mq = -1.6384e-1;
Mtheta = 0;

Xde = 2.6533e-3;
Zde = -6.8562;
Mde = -5.4446;

A = [Xu, Xw, Xq, Xtheta;
     Zu, Zw, Zq, Ztheta;
     Mu, Mw, Mq, Mtheta;
     0,  0,  1,  0];

B = [Xde; Zde; Mde; 0];

C = eye(4);
D = zeros(4,1);

U0 = 178;
g = 9.81;
theta0 = 0;

m = 17642;
ev = eig(A);
sys_ss = ss(A, B, C, D);
sys_tf = tf(sys_ss);
%% LATERAL-DIRECTIONAL DYNAMICS (F-4 Phantom, Roskam data via Mach 0.9, 35000 ft)
V0_lat = 266.84;

A_lat = [-0.0965, 0, 0, 9.81;
          -0.0697, -1.2327, 0.3595, 0;
          0.01947, -0.03307, -0.24803, 0;
          0, 1, 0, 0];

B_lat = [0.6055, 3.5959;
         -9.759, 1.3942;
         0.04156, -2.7427;
         0, 0];

C_lat = eye(4);
D_lat = zeros(4,2);

sys_ss_lat = ss(A_lat, B_lat, C_lat, D_lat);
sys_tf_lat = tf(sys_ss_lat);